apiVersion: v1
kind: Service
metadata:
  name: java-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: java-web-app1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080