apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-web-app
  name: java-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-web-app
  template:
    metadata:
      labels:
        app: java-web-app
    spec:
      containers:
      - image: tshethp/java-struts2-cve-2018-11776
        name: java-web-app
        ports:
        - containerPort: 8080