apiVersion: v1
kind: Service
metadata:
  name: file-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: file-uploader
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80