apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: file-uploader
  name: file-uploader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-uploader
  template:
    metadata:
      labels:
        app: file-uploader
    spec:
      containers:
      - image: tshethp/vulnerable_site_example
        name: file-uploader
        ports:
        - containerPort: 80