apiVersion: v1
kind: Service
metadata:
  name: drupal-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: drupal-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80